#########
## NOTE #
# 1. Copy to owesp32.toml
# 2. Edit your specifics (server, wifi, token, etc
# 3. Upload with rest of files to ESP32 device
#########

# ESP32 configuration file for owlogger client
# in TOML format https://toml.io/en/
#
# See https://github.com/alfille/owlogger

# blank lines and text after '#' comments are ignored

# server location (external)
# usually a valid subdomain address
#server=https://owlogger.mypvs.net

# onewire
# physical gpio pin configured for 1-wire
pin=12

# name
# to distinguish multiple sources
# Choose a real, insightful name
name="esp32"

# Authentification token (JWT)
# choose something better than this
# Server must match
token="simple_string"

# Temperature
# only one is needed and default is Fahrenheit
Fahenheit=true
# Celsius=true

# period in minutes
period=15

[[wifi]]
ssid="test"
password="secret"

# Can add more [[wifi]] sections
